Resources:
  EventQueue:
    Type: "AWS::SQS::Queue"
    DeletionPolicy: ${self:custom.deletionPolicy.${opt:stage}, self:custom.deletionPolicy.other}
    Properties:
      QueueName: sqs-${self:custom.EventQueue}
      VisibilityTimeout: 899